<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [2]:
%%sql

Select *
FROM sales
Limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [3]:
%%sql

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

In [4]:
%%sql

SELECT *
FROM currencyexchange
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

         date fromcurrency tocurrency  exchange
0  2015-01-01          AUD        AUD      1.00
1  2015-01-01          AUD        CAD      0.95
2  2015-01-01          AUD        EUR      0.67
3  2015-01-01          AUD        GBP      0.53
4  2015-01-01          AUD        USD      0.82
5  2015-01-01          CAD        AUD      1.05
6  2015-01-01          CAD        CAD      1.00
7  2015-01-01          CAD        EUR      0.71
8  2015-01-01          CAD        GBP      0.55
9  2015-01-01          CAD        USD      0.86

In [5]:
%%sql

SELECT *
FROM store
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,storekey,storecode,geoareakey,countrycode,countryname,state,opendate,closedate,description,squaremeters,status
0,10,1,1,AU,Australia,Australian Capital Territory,2008-01-01,None,Contoso Store Australian Capital Territory,595.00,None
1,20,2,3,AU,Australia,Northern Territory,2008-01-12,2016-07-07,Contoso Store Northern Territory,665.00,Closed
2,30,3,5,AU,Australia,South Australia,2012-01-07,2015-08-08,Contoso Store South Australia,2000.00,Restructured
3,35,3,5,AU,Australia,South Australia,2015-12-08,None,Contoso Store South Australia,3000.00,None
4,40,4,6,AU,Australia,Tasmania,2010-01-01,None,Contoso Store Tasmania,2000.00,None
5,50,5,7,AU,Australia,Victoria,2015-12-09,None,Contoso Store Victoria,2000.00,None
6,60,6,8,AU,Australia,Western Australia,2010-01-01,None,Contoso Store Western Australia,2000.00,None
7,70,7,12,CA,Canada,New Brunswick,2007-05-07,2014-03-09,Contoso Store New Brunswick,1105.00,Restructured
8,72,7,12,CA,Canada,New Brunswick,2015-01-11,2018-02-02,Contoso Store New Brunswick,1500.00,Restructured
9,74,7,12,CA,Canada,New Brunswick,2018-06-02,None,Contoso Store New Brunswick,3500.00,None

In [6]:
%%sql

SELECT *
FROM customer
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,geoareakey,startdt,enddt,continent,gender,title,givenname,middleinitial,surname,...,zipcode,country,countryfull,birthday,age,occupation,company,vehicle,latitude,longitude
0,15,4,1990-09-10,2034-07-29,Australia,male,Mr.,Julian,A,McGuigan,...,4357,AU,Australia,1965-03-24,55,Border Patrol agent,Cut Rite Lawn Care,2000 Peugeot Kart Up,-27.83,151.17
1,23,8,1995-08-11,2045-01-26,Australia,female,Ms.,Rose,H,Dash,...,6055,AU,Australia,1990-05-10,30,Agricultural and food scientist,Rack N Sack,2005 Volvo XC90,-31.92,116.05
2,36,2,1992-03-12,2044-05-14,Australia,female,Ms.,Annabelle,J,Townsend,...,2304,AU,Australia,1964-07-16,56,Special education teacher,id Boutiques,1999 Lancia Lybra,-32.88,151.71
3,120,6,1983-07-23,2033-08-09,Australia,male,Mr.,Jamie,H,Hetherington,...,7256,AU,Australia,1946-12-11,74,Dental laboratory technician,Showbiz Pizza Place,2006 Dodge Durango,-39.77,144.02
4,180,7,1987-11-26,2026-10-14,Australia,male,Mr.,Gabriel,P,Bosanquet,...,3505,AU,Australia,1955-04-24,65,Administrative support specialist,Dubrow's Cafeteria,1995 Morgan Plus 4,-34.13,142.14
5,185,2,1990-08-01,2029-05-28,Australia,female,Mrs.,Gabrielle,B,Castella,...,2469,AU,Australia,1980-02-23,40,Management dietitian,d.e.m.o.,1997 Alpina B6,-29.01,152.84
6,189,7,2008-07-05,2017-11-01,Australia,female,Ms.,Hayley,C,Jull,...,3377,AU,Australia,1960-04-18,60,Sculptor,Asian Plan,2006 Alpina B5,-37.34,142.91
7,210,2,1980-09-28,2030-05-08,Australia,female,Mrs.,Natalie,L,Hilder,...,2632,AU,Australia,1950-11-23,70,Motel desk clerk,Enrich Garden Services,1995 Ford Fairlane,-36.84,149.05
8,225,7,1985-06-25,2017-09-25,Australia,male,Mr.,Hunter,J,Hutchins,...,3763,AU,Australia,1978-07-20,42,Teletype operator,Mr. Good Buys,2012 Lexus GX,-37.51,145.44
9,243,2,1982-02-07,2027-02-09,Australia,female,Ms.,Maya,J,Atherton,...,2446,AU,Australia,1954-05-15,66,Pilates instructor,Franklin Music,1995 Chevrolet Caprice,-31.36,152.39

In [7]:
%%sql

SELECT *
FROM product
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3
2,3,101003,Contoso 1G MP3 Player E100 White,"Contoso, Ltd",Contoso,White,ounces,4.50,7.40,14.52,1,Audio,101,MP4&MP3
3,4,101004,Contoso 2G MP3 Player E200 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.50,11.00,21.57,1,Audio,101,MP4&MP3
4,5,101005,Contoso 2G MP3 Player E200 Red,"Contoso, Ltd",Contoso,Red,ounces,2.40,11.00,21.57,1,Audio,101,MP4&MP3
5,6,101006,Contoso 2G MP3 Player E200 Black,"Contoso, Ltd",Contoso,Black,ounces,8.80,11.00,21.57,1,Audio,101,MP4&MP3
6,7,101007,Contoso 2G MP3 Player E200 Blue,"Contoso, Ltd",Contoso,Blue,ounces,2.10,11.00,21.57,1,Audio,101,MP4&MP3
7,8,101008,Contoso 4G MP3 Player E400 Silver,"Contoso, Ltd",Contoso,Silver,ounces,5.60,30.58,59.99,1,Audio,101,MP4&MP3
8,9,101009,Contoso 4G MP3 Player E400 Black,"Contoso, Ltd",Contoso,Black,ounces,2.10,30.58,59.99,1,Audio,101,MP4&MP3
9,10,101010,Contoso 4G MP3 Player E400 Green,"Contoso, Ltd",Contoso,Green,ounces,11.00,30.58,59.99,1,Audio,101,MP4&MP3

In [8]:
%%sql

SELECT *
FROM date
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,date,datekey,year,yearquarter,yearquarternumber,quarter,yearmonth,yearmonthshort,yearmonthnumber,month,monthshort,monthnumber,dayofweek,dayofweekshort,dayofweeknumber,workingday,workingdaynumber
0,2015-01-01,20150101,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,0,0
1,2015-01-02,20150102,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,1
2,2015-01-03,20150103,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,1
3,2015-01-04,20150104,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Sunday,Sun,1,0,1
4,2015-01-05,20150105,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Monday,Mon,2,1,2
5,2015-01-06,20150106,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Tuesday,Tue,3,1,3
6,2015-01-07,20150107,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Wednesday,Wed,4,1,4
7,2015-01-08,20150108,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,1,5
8,2015-01-09,20150109,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,6
9,2015-01-10,20150110,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,6

In [9]:
%%sql

SELECT *
FROM information_schema.columns

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2046 rows affected.

,table_catalog,table_schema,table_name,column_name,ordinal_position,column_default,is_nullable,data_type,character_maximum_length,character_octet_length,...,is_identity,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle,is_generated,generation_expression,is_updatable
0,contoso_100k,pg_catalog,pg_attribute,attinhcount,21,None,NO,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
1,contoso_100k,pg_catalog,pg_stat_gssapi,pid,1,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,NO
2,contoso_100k,pg_catalog,pg_stat_gssapi,gss_authenticated,2,None,YES,boolean,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,NO
3,contoso_100k,pg_catalog,pg_attribute,attcollation,22,None,NO,oid,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
4,contoso_100k,pg_catalog,pg_stat_gssapi,encrypted,4,None,YES,boolean,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2041,contoso_100k,pg_catalog,pg_type,typdefault,31,None,YES,text,NaN,1073741824.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
2042,contoso_100k,pg_catalog,pg_statistic_ext,stxname,3,None,NO,name,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
2043,contoso_100k,pg_catalog,pg_statio_user_tables,relname,3,None,YES,name,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,NO
2044,contoso_100k,pg_catalog,pg_statio_user_tables,schemaname,2,None,YES,name,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,NO
2045,contoso_100k,pg_catalog,pg_statio_sys_tables,relname,3,None,YES,name,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,NO

In [10]:
%%sql

Select
  orderdate,
 quantity * netprice * exchangerate AS net_revenue
FROM Sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue
0  2015-01-01        63.49
1  2015-01-01       423.28
2  2015-01-01       108.75
3  2015-01-01      1146.75
4  2015-01-01       950.25
5  2015-01-01      1302.91
6  2015-01-01        58.73
7  2015-01-01       224.98
8  2015-01-01       263.11
9  2015-01-01       578.52

In [11]:
%%sql

SELECT
  s.orderdate,
  COUNT(DISTINCT s.customerkey) AS total_customers,
  COUNT(DISTINCT CASE WHEN c.continent = 'Europe' THEN s.customerkey END) AS eu_customers
FROM
  sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
GROUP BY
  s.orderdate
ORDER BY
  s.orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3294 rows affected.

       orderdate  total_customers  eu_customers
0     2015-01-01                9             3
1     2015-01-02                6             1
2     2015-01-03               11             6
3     2015-01-05                4             0
4     2015-01-06                5             2
...          ...              ...           ...
3289  2024-04-16               14             4
3290  2024-04-17               22             5
3291  2024-04-18               25            10
3292  2024-04-19               19             5
3293  2024-04-20               35            15

[3294 rows x 3 columns]

In [12]:
%%sql

SELECT
  p.categoryname,
  SUM(s.quantity * s.exchangerate * s.netprice) AS net_revenue,
  SUM(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN s.quantity * s.exchangerate * s.netprice Else 0 END) AS net_revnue_2022
FROM
  sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  net_revenue  net_revnue_2022
0                          Audio   5312898.10        766938.21
1        Cameras and camcorders   18520360.66       2382532.56
2                    Cell phones  32624265.72       8119665.07
3                      Computers  90619022.05      17862213.49
4                 Games and Toys   1668574.13        316127.30
5                Home Appliances  26607245.54       6612446.68
6  Music, Movies and Audio Books  10588311.00       2989297.28
7                   TV and Video  20466861.38       5815336.61

In [13]:
%%sql

SELECT
  p.categoryname,
  PERCENTILE_CONT(.5) WITHIN GROUP (ORDER BY (CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.exchangerate * s.netprice) END)) AS net_revnue_2022
FROM
  sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  net_revnue_2022
0                          Audio           257.21
1        Cameras and camcorders            651.46
2                    Cell phones           418.60
3                      Computers           809.70
4                 Games and Toys            33.78
5                Home Appliances           791.00
6  Music, Movies and Audio Books           186.58
7                   TV and Video           730.46

In [14]:
%%sql

SELECT
  orderdate,
  netprice,
  quantity,
  CASE
      WHEN quantity >= 2 AND netprice >=100 THEN 'Multiple High Value Order'
      WHEN netprice >100 THEN 'SIngle High Value Item'
      WHEN quantity >= 2 THEN 'Multiple Standard Order'
      ELSE 'Standard Order'
      END AS order_type
FROM sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  netprice  quantity                 order_type
0  2015-01-01     98.97         1             Standard Order
1  2015-01-01    659.78         1     SIngle High Value Item
2  2015-01-01     54.38         2    Multiple Standard Order
3  2015-01-01    286.69         4  Multiple High Value Order
4  2015-01-01    135.75         7  Multiple High Value Order
5  2015-01-01    434.30         3  Multiple High Value Order
6  2015-01-01     58.73         1             Standard Order
7  2015-01-01     74.99         3    Multiple Standard Order
8  2015-01-01    113.57         2  Multiple High Value Order
9  2015-01-01    499.45         1     SIngle High Value Item

In [15]:
%%sql

SELECT
  orderdate,
  DATE_TRUNC('month', orderdate)::date AS order_month
FROM
  sales
ORDER BY RANDOM()
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate order_month
0  2023-05-20  2023-05-01
1  2019-01-17  2019-01-01
2  2023-10-14  2023-10-01
3  2022-08-26  2022-08-01
4  2023-06-19  2023-06-01
5  2023-12-21  2023-12-01
6  2022-10-01  2022-10-01
7  2020-02-26  2020-02-01
8  2023-04-23  2023-04-01
9  2017-03-07  2017-03-01

In [16]:
%%sql

SELECT
  CURRENT_DATE

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  current_date
0   2025-06-10

In [17]:
%%sql

SELECT
  CURRENT_DATE,
  s.orderdate,
  p.categoryname,
  SUM(s.quantity * s.exchangerate * s.netprice) AS net_revenue
  FROM
    sales s
LEFT JOIN product p ON s.productkey = p.productkey
WHERE
  orderdate >= CURRENT_DATE - INTERVAL '5 years'
GROUP BY
  s.orderdate,
  p.categoryname
ORDER BY
  s.orderdate,
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10077 rows affected.

      current_date   orderdate                   categoryname  net_revenue
0       2025-06-10  2020-06-10                          Audio       953.76
1       2025-06-10  2020-06-10        Cameras and camcorders       9579.02
2       2025-06-10  2020-06-10                    Cell phones      4897.38
3       2025-06-10  2020-06-10                      Computers     12417.44
4       2025-06-10  2020-06-10                 Games and Toys        99.25
...            ...         ...                            ...          ...
10072   2025-06-10  2024-04-20                      Computers     58353.68
10073   2025-06-10  2024-04-20                 Games and Toys      1744.30
10074   2025-06-10  2024-04-20                Home Appliances      1562.04
10075   2025-06-10  2024-04-20  Music, Movies and Audio Books      4949.43
10076   2025-06-10  2024-04-20                   TV and Video      9841.91

[10077 rows x 4 columns]

In [18]:
%%sql

SELECT INTERVAL '5 centuries'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

               interval
0  182500 days, 0:00:00

In [19]:
%%sql

SELECT
  DATE_PART('years', orderdate) AS order_year,
  AVG(EXTRACT(DAYS FROM AGE(deliverydate, orderdate))) AS avg_processing_time
FROM
  sales
WHERE
  orderdate >= CURRENT_DATE - INTERVAL '5 years'
GROUP BY
  order_year
ORDER BY
  order_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

   order_year     avg_processing_time
0     2020.00  0.97197951190117505273
1     2021.00      1.3570381602223907
2     2022.00      1.6233962099189089
3     2023.00      1.7526721219713730
4     2024.00  1.66696278748396012240

In [20]:
%%sql

Select
  orderkey,
  linenumber,
  customerkey,
  (quantity * netprice * exchangerate) AS net_revenue,
  AVG(quantity * netprice * exchangerate) OVER () AS ang_net_revenue_all_orders,
  AVG(quantity * netprice * exchangerate) OVER (PARTITION BY customerkey) AS ang_net_revenue_all_orders_customer
FROM Sales
ORDER BY
  customerkey
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,customerkey,net_revenue,ang_net_revenue_all_orders,ang_net_revenue_all_orders_customer
0,2259001,0,15,2217.41,1032.69,2217.41
1,1305016,0,180,525.31,1032.69,836.74
2,3162018,0,180,71.36,1032.69,836.74
3,3162018,1,180,1913.55,1032.69,836.74
4,1613010,0,185,1395.52,1032.69,1395.52
5,505008,0,243,287.67,1032.69,287.67
6,1451007,0,387,1608.10,1032.69,517.32
7,1451007,1,387,619.77,1032.69,517.32
8,1451007,2,387,97.05,1032.69,517.32
9,1451007,3,387,45.62,1032.69,517.32

In [21]:
%%sql

Select
  orderdate,
  orderkey * 10 + linenumber AS order_line_number,
  (quantity * netprice * exchangerate) AS net_revenue,
  SUM(quantity * netprice * exchangerate) OVER(PARTITION BY orderdate) AS daily_net_revenue,
  (quantity * netprice * exchangerate) * 100 /  SUM(quantity * netprice * exchangerate) OVER(PARTITION BY orderdate) AS pct_daily_revenue
FROM sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,order_line_number,net_revenue,daily_net_revenue,pct_daily_revenue
0,2015-01-01,10000,63.49,11640.80,0.55
1,2015-01-01,10001,423.28,11640.80,3.64
2,2015-01-01,10010,108.75,11640.80,0.93
3,2015-01-01,10020,1146.75,11640.80,9.85
4,2015-01-01,10021,950.25,11640.80,8.16
5,2015-01-01,10022,1302.91,11640.80,11.19
6,2015-01-01,10023,58.73,11640.80,0.50
7,2015-01-01,10030,224.98,11640.80,1.93
8,2015-01-01,10040,263.11,11640.80,2.26
9,2015-01-01,10041,578.52,11640.80,4.97

In [22]:
%%sql

WITH yearly_cohort AS (
SELECT DISTINCT
  customerkey,
  EXTRACT(YEAR FROM MIN(orderdate) OVER(PARTITION BY customerkey)) AS cohort_year
FROM sales
)

SELECT
  y.cohort_year,
  EXTRACT(YEAR FROM orderdate) AS purchase_year,
  SUM(quantity * netprice * exchangerate) AS net_revenue
FROM sales s
LEFT JOIN yearly_cohort y ON s.customerkey = y.customerkey
GROUP BY
  y.cohort_year,
  purchase_year
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  cohort_year purchase_year  net_revenue
0        2019          2022   4848980.74
1        2020          2020   7265759.44
2        2018          2022   4534295.81
3        2017          2018   1407065.13
4        2016          2022   2164681.10
5        2021          2021  12635597.87
6        2018          2024    936833.89
7        2018          2023   3271753.92
8        2023          2023  14345184.96
9        2020          2024    312983.02

In [23]:
%%sql

WITH yearly_cohort AS (
SELECT DISTINCT
  customerkey,
  EXTRACT(YEAR FROM MIN(orderdate) OVER(PARTITION BY customerkey)) AS cohort_year,
  EXTRACT(YEAR FROM orderdate) AS purchase_year
FROM sales
)

SELECT DISTINCT
  cohort_year,
  purchase_year,
  COUNT(customerkey) OVER(PARTITION BY purchase_year, cohort_year) AS num_customers
FROM yearly_cohort
ORDER BY
  cohort_year,
  purchase_year
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  cohort_year purchase_year  num_customers
0        2015          2015           2825
1        2015          2016            126
2        2015          2017            149
3        2015          2018            348
4        2015          2019            388
5        2015          2020            171
6        2015          2021            295
7        2015          2022            600
8        2015          2023            499
9        2015          2024            146

In [24]:
%%sql

SELECT
  customerkey,
  orderdate,
  (quantity * netprice * exchangerate) AS net_revenue,
  COUNT(*) OVER(
    PARTITION BY customerkey
                ORDER BY orderdate
) AS running_order_count,
 AVG(quantity * netprice * exchangerate) OVER(
    PARTITION BY customerkey
                ORDER BY orderdate
)
FROM
  sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

        customerkey   orderdate  net_revenue  running_order_count     avg
0                15  2021-03-08      2217.41                    1 2217.41
1               180  2018-07-28       525.31                    1  525.31
2               180  2023-08-28        71.36                    3  836.74
3               180  2023-08-28      1913.55                    3  836.74
4               185  2019-06-01      1395.52                    1 1395.52
...             ...         ...          ...                  ...     ...
199868      2099711  2016-08-13      2067.75                    1 2067.75
199869      2099711  2017-08-14      3940.92                    2 3004.34
199870      2099743  2022-03-17       375.57                    2  234.81
199871      2099743  2022-03-17        94.05                    2  234.81
199872      2099743  2023-02-11       598.46                    3  356.03

[199873 rows x 5 columns]

In [25]:
%%sql

WITH row_numbering AS (
    SELECT
      ROW_NUMBER() OVER(PARTITION BY orderdate
      ORDER BY orderdate,
                  orderkey,
                  linenumber
  ) AS row_num,
  *
  FROM sales
)

SELECT *
FROM row_numbering
WHERE orderdate > '2015-01-01'
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,row_num,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1,2000,0,2015-01-02,2015-01-02,1639738,530,1613,5,65.99,59.39,33.65,USD,1.00
1,2,2001,0,2015-01-02,2015-01-15,2085372,999999,2182,2,1237.50,1237.50,410.01,USD,1.00
2,3,2002,0,2015-01-02,2015-01-02,1732602,510,1822,2,22.40,22.40,11.42,USD,1.00
3,4,2002,1,2015-01-02,2015-01-02,1732602,510,49,5,149.96,149.96,68.96,USD,1.00
4,5,2003,0,2015-01-02,2015-01-02,728917,300,1674,2,4.89,4.89,2.49,EUR,0.83
5,6,2003,1,2015-01-02,2015-01-02,728917,300,369,1,1747.50,1555.28,803.60,EUR,0.83
6,7,2004,0,2015-01-02,2015-01-02,1724183,570,1654,2,155.99,155.99,51.68,USD,1.00
7,8,2005,0,2015-01-02,2015-01-02,2054699,480,460,1,749.75,712.26,382.25,USD,1.00
8,1,3000,0,2015-01-03,2015-01-03,1793739,500,108,3,99.74,97.75,45.87,USD,1.00
9,2,3000,1,2015-01-03,2015-01-03,1793739,500,1684,3,11.82,11.00,3.92,USD,1.00

In [26]:
%%sql

SELECT
  customerkey,
  COUNT(*) AS total_orders,
  ROW_NUMBER() OVER(ORDER BY COUNT(*) DESC) AS total_row_order_num,
  RANK() OVER(ORDER BY COUNT(*) DESC) AS total_orders_rank_,
  DENSE_RANK() OVER(ORDER BY COUNT(*) DESC) AS total_orders_dense_rank_
FROM sales
GROUP BY
customerkey
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,total_orders,total_row_order_num,total_orders_rank_,total_orders_dense_rank_
0,1834524,31,1,1,1
1,1375597,30,2,2,2
2,249557,27,3,3,3
3,1495941,26,4,4,4
4,459519,26,5,4,4
5,1801215,26,6,4,4
6,1219056,25,7,7,5
7,1876222,24,8,8,6
8,1427444,24,9,8,6
9,759419,24,10,8,6

In [27]:
%%sql

WITH monthly_revenue AS (
  SELECT
    TO_CHAR(orderdate, 'YYYY-MM') AS month,
    SUM(quantity * netprice * exchangerate) AS net_revenue
FROM sales
WHERE EXTRACT(YEAR FROM orderdate) = 2023
GROUP by month
ORDER BY month
)

SELECT
  *,
  LAG(net_revenue) OVER(ORDER BY month) AS previous_month_revenue,
  100 * (net_revenue -  LAG(net_revenue) OVER(ORDER BY month))/ LAG(net_revenue) OVER(ORDER BY month) AS MoM_growth
FROM monthly_revenue

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  previous_month_revenue  mom_growth
0   2023-01   3664431.34                     NaN         NaN
1   2023-02   4465204.57              3664431.34       21.85
2   2023-03   2244316.52              4465204.57      -49.74
3   2023-04   1162796.16              2244316.52      -48.19
4   2023-05   2943005.99              1162796.16      153.10
5   2023-06   2864500.03              2943005.99       -2.67
6   2023-07   2337639.34              2864500.03      -18.39
7   2023-08   2623919.79              2337639.34       12.25
8   2023-09   2622774.85              2623919.79       -0.04
9   2023-10   2551322.61              2622774.85       -2.72
10  2023-11   2700103.38              2551322.61        5.83
11  2023-12   2928550.93              2700103.38        8.46

In [37]:
%%sql
WITH yearly_cohort AS (
  SELECT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate)) AS cohort_year,
    SUM(quantity * netprice * exchangerate) AS customer_ltv
  FROM sales
  GROUP BY
    customerkey
), cohort_summary AS (
  SELECT
    cohort_year,
    customerkey,
    customer_ltv,
    AVG(customer_ltv) OVER(PARTITION BY cohort_year) AS avg_cohort_ltv
  FROM yearly_cohort
  ORDER BY
    cohort_year,
    customerkey
) , cohort_final_year AS (
  SELECT DISTINCT
      cohort_year,
      avg_cohort_ltv
  FROM cohort_summary
  ORDER BY
    cohort_year
)

SELECT
  *,
  LAG(avg_cohort_ltv) OVER (ORDER BY cohort_year) AS previous_cohort_ltv,
  ((avg_cohort_ltv) - LAG(avg_cohort_ltv) OVER (ORDER BY cohort_year))/
  LAG(avg_cohort_ltv) OVER (ORDER BY cohort_year)
FROM cohort_final_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  cohort_year  avg_cohort_ltv  previous_cohort_ltv  ?column?
0        2015         5271.59                  NaN       NaN
1        2016         5404.92              5271.59      0.03
2        2017         5403.08              5404.92     -0.00
3        2018         4896.64              5403.08     -0.09
4        2019         4731.95              4896.64     -0.03
5        2020         3933.32              4731.95     -0.17
6        2021         3943.33              3933.32      0.00
7        2022         3315.52              3943.33     -0.16
8        2023         2543.18              3315.52     -0.23
9        2024         2037.55              2543.18     -0.20

In [41]:
%%sql
WITH monthly_revenue AS(
  SELECT
      TO_CHAR(orderdate, 'YYYY-MM') AS month,
      SUM(quantity * netprice * exchangerate) AS net_revenue
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP by month
  ORDER BY month
)

SELECT
  month,
  net_revenue,
  AVG(net_revenue) OVER(
    ORDER BY month
    ROWS BETWEEN CURRENT ROW AND CURRENT ROW
  )
FROM monthly_revenue

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue        avg
0   2023-01   3664431.34 3664431.34
1   2023-02   4465204.57 4465204.57
2   2023-03   2244316.52 2244316.52
3   2023-04   1162796.16 1162796.16
4   2023-05   2943005.99 2943005.99
5   2023-06   2864500.03 2864500.03
6   2023-07   2337639.34 2337639.34
7   2023-08   2623919.79 2623919.79
8   2023-09   2622774.85 2622774.85
9   2023-10   2551322.61 2551322.61
10  2023-11   2700103.38 2700103.38
11  2023-12   2928550.93 2928550.93